package threes.model;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Titouan HETMANIAK
 */
public class ThreesFrame extends javax.swing.JFrame {
    
    
    private void initGame() {  
        model = new GameModel();
        model.reset();
        cells = new JButton[4][4];
    }
    
       
    private void initComponents() {

        gridPanel = new JPanel();
        movesLabel = new JLabel("Coups : 0");
        infoLabel = new JLabel("Utilise les flèches");
        resetButton = new JButton("Recommencer");

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("THREES - Swing");
        setResizable(false);

        gridPanel.setLayout(new GridLayout(4, 4, 8, 8));
        gridPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        resetButton.addActionListener(e -> resetGame());

        JPanel topPanel = new JPanel(new BorderLayout());
        topPanel.add(movesLabel, BorderLayout.WEST);
        topPanel.add(infoLabel, BorderLayout.CENTER);
        topPanel.add(resetButton, BorderLayout.EAST);

        add(topPanel, BorderLayout.NORTH);
        add(gridPanel, BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ThreesFrame.class.getName());

    /**
     * Creates new form ThreesFrame
     */
    public ThreesFrame() {
        initComponents();      // NetBeans
        initGame();            // logique
        initGrid();            // boutons
        initKeyBindings();     // clavier
        updateView();          // affichage
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ThreesFrame().setVisible(true));
    }

    private void initGrid() {
        gridPanel.removeAll();

        for (int r = 0; r < 4; r++) {
            for (int c = 0; c < 4; c++) {
                JButton btn = new JButton();
                btn.setEnabled(false);
                btn.setFont(new Font("Arial", Font.BOLD, 22));
                btn.setPreferredSize(new Dimension(80, 80));
                cells[r][c] = btn;
                gridPanel.add(btn);
            }
        }
    }

    private void initKeyBindings() {

        JComponent root = getRootPane();
        InputMap im = root.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap am = root.getActionMap();

        im.put(KeyStroke.getKeyStroke("UP"), "up");
        im.put(KeyStroke.getKeyStroke("DOWN"), "down");
        im.put(KeyStroke.getKeyStroke("LEFT"), "left");
        im.put(KeyStroke.getKeyStroke("RIGHT"), "right");

        am.put("up", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                play(Direction.UP);
            }
        });

        am.put("down", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                play(Direction.DOWN);
            }
        });

        am.put("left", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                play(Direction.LEFT);
            }
        });

        am.put("right", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                play(Direction.RIGHT);
            }
        });
    }

    private void updateView() {

        int[][] grid = model.getGrid();
        movesLabel.setText("Coups : " + model.getMovesCount());

        for (int r = 0; r < 4; r++) {
            for (int c = 0; c < 4; c++) {

                int v = grid[r][c];
                JButton btn = cells[r][c];

                btn.setText(v == 0 ? "" : String.valueOf(v));
                btn.setBackground(getColor(v));
            }
        }
    }

        private void resetGame() {
        model.reset();
        infoLabel.setText("Nouvelle partie");
        updateView();
    }

   
        
    

    

    

    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

